modified:   modchecker 	modified:   moddownloader 	modified:   modfunctions 	modified:   modunpacker

diff --git a/modfunctions b/modfunctions
--- a/modfunctions
+++ b/modfunctions
@@ -12,7 +12,7 @@ logs="${scriptpath}/logs"
 [ ! -d "$logs" ] && mkdir "$logs"
 
 function output_msg {
- grep ^ERROR <<<"$msg" &>/dev/null && echo "$(date) - [App ID: $appid] - $msg" >> "${logs}/${scriptname}-errors.txt"
+ grep ^ERROR <<<"$msg" &>/dev/null && echo "$(date) - [App ID: $appid] - $msg" >> "${logs}/$(awk '{sub(/ /,""); print tolower($0)}' <<<$scriptname)-errors.txt"
  echo -e "[${scriptname}] $msg"
 }
 
@@ -25,10 +25,10 @@ scriptname="$1"
 [ -z "$3" ] && [ ! -f "${scriptpath}/mods.conf" ] && \
  msg="ERROR: Syntax is wrong. Mod ID(s) is missing. Exiting." && output_msg && exit 1
 [ ! -z "$2" ] && appid="$2"
-[ ! -z "$3" ] && modid=( $(echo "$*" | sed "s/$appid //g") )
+[ ! -z "$3" ] && modid=( $(echo "$*" | sed "s/$appid //g" | tr -d '[:alpha:]') )
 if [ -z "$2" ] && [ -f "${scriptpath}/mods.conf" ]; then
  conf="${scriptpath}/mods.conf"
- eval steaminstallation=$(grep "^steaminstallation" "$conf" | cut -d "=" -f 2)
+ eval steaminstallation=$(grep "^steaminstallation" "$conf" | grep -v "#" | cut -d "=" -f 2)
  appid=$(grep "^appid" "$conf" | cut -d "=" -f 2)
  modid=( $(grep "^modid" "$conf" | cut -d "=" -f 2) )
  eval server=( $(grep "^server" "$conf" | cut -d "=" -f 2) )
@@ -38,7 +38,7 @@ fi
 # Error handling
 [ -z "$steaminstallation" ] && msg="ERROR: Steam installation path is not set. Exiting." && output_msg && exit 1
 [ -z "$appid" ] && msg="ERROR: App ID is not set. Exiting." && output_msg && exit 1
-[ "${#server[@]}" -eq 0 ] && msg="ERROR: Server(s) path is not set. Exiting." && output_msg && exit 1
+[ "$scriptname" != "Mod Downloader" ] && [ "${#server[@]}" -eq 0 ] && msg="ERROR: Server(s) path is not set. Exiting." && output_msg && exit 1
 [ "${#modid[@]}" -eq 0 ] && msg="ERROR: Mod ID(s) is not set. Exiting." && output_msg && exit 1
 [ "$scriptname" = "Mod Downloader" ] && [ -z "$steamcmd" ] && msg="ERROR: steamcmd path is not set. Exiting." && output_msg && exit 1
 [ "$scriptname" = "Mod Checker" ] && [ ! -f "${scriptpath}/moddownloader" ] && msg="ERROR: moddownloader script now found. Exiting." && output_msg && exit 1
