modified:   modinfo

diff --git a/modinfo b/modinfo
--- a/modinfo
+++ b/modinfo
@@ -33,11 +33,12 @@ function bytesToHuman {
 for i in "${modid[@]}"; do
  mod=$(curl -s -i -X POST -H "Content-Type:application/x-www-form-urlencoded" -d "itemcount=1" -d "publishedfileids[0]=${i}" \
   'https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/?format=xml')
- modname=$(grep "<title>" <<<"$mod" | sed -e 's/<title>//g' -e 's/<\/title>//g' -e "s/&apos;/'/g" -e 's/\t//g')
+ chk=$(grep -q "<title>" <<<"$mod"; echo $?)
+ [ "$chk" -ne 0 ] && echo "[Mod ID: ${i}] Not Found!" && continue
+ modname=$(grep "<title>" <<<"$mod" | sed -e 's/<title>//g' -e 's/<\/title>//g' -e "s/&apos;/'/g" | awk 'gsub("\t",""); {pring $0}')
  modsize=$(grep "<file_size>" <<<"$mod" | sed -e 's/<file_size>//g' -e 's/<\/file_size>//g' | xargs)
  modsize=$(bytesToHuman "$modsize")
  appid=$(grep "<consumer_app_id>" <<<"$mod" | sed -e 's/<consumer_app_id>//g' -e 's/<\/consumer_app_id>//g' | xargs)
  modinfo="[App ID: ${appid}] [Mod ID: ${i}] Mod name: $modname [${modsize}]"
- [ -z "$modname" ] && modinfo="[Mod ID: ${i}] Mod name: N/A"
  echo "$modinfo"
 done
